-- ============================================
-- TABLA DE ROLES
-- ============================================
CREATE TABLE TB_ROLES (
  ID_ROLE SERIAL PRIMARY KEY,
  NAME_ROLE CHAR(1) NOT NULL UNIQUE
);

-- Insertar roles por defecto
INSERT INTO TB_ROLES (NAME_ROLE) VALUES
('A'),
('R'),
('C');

-- ============================================
-- TABLA DE USUARIOS (extendida de Supabase Auth)
-- ============================================
CREATE TABLE TB_USERS (
  ID_USER UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  ID_ROLE INT NOT NULL REFERENCES TB_ROLES(ID_ROLE),
  EMAIL VARCHAR(100) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  PHONE VARCHAR(15) NOT NULL,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP DEFAULT NOW()
);

-- ============================================
-- TABLA DE CATEGORÍAS DEL MENÚ
-- ============================================
CREATE TABLE TB_CATEGORIES (
  ID_CAT SERIAL PRIMARY KEY,
  NAME_CAT VARCHAR(100) NOT NULL UNIQUE,
  DESCRIPTION TEXT,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP DEFAULT NOW()
);

-- Categorías ejemplo
INSERT INTO TB_CATEGORIES (NAME_CAT, DESCRIPTION) VALUES
('Cafés', 'Variedades de café caliente y frío'),
('Postres', 'Pasteles, tartas y dulces'),
('Desayunos', 'Opciones para empezar el día'),
('Bebidas', 'Jugos, smoothies y más');

-- ============================================
-- TABLA DE ITEMS DEL MENÚ
-- ============================================
CREATE TABLE TB_ITEMS (
  ID_ITEM SERIAL PRIMARY KEY,
  ID_CAT INT NOT NULL REFERENCES TB_CATEGORIES(ID_CAT) ON DELETE CASCADE,
  NAME VARCHAR(150) NOT NULL,
  DESCRIPTION TEXT,
  PRICE DECIMAL(10, 2) NOT NULL CHECK (PRICE >= 0),
  IMAGE_URL TEXT,
  IS_AVAILABLE BOOLEAN DEFAULT TRUE,
  IS_FEATURED BOOLEAN DEFAULT FALSE, -- Para destacados
  CREATED_AT TIMESTAMP DEFAULT NOW()
);

-- ============================================
-- TABLA DE MESAS
-- ============================================
CREATE TABLE TB_TABLES (
  ID_TABLE SERIAL PRIMARY KEY,
  TABLE_NUMBER INT NOT NULL UNIQUE,
  CAPACITY INT NOT NULL CHECK (CAPACITY > 0),
  LOCATION VARCHAR(50), -- 'Interior', 'Terraza', 'VIP', etc.
  IS_AVAILABLE BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP DEFAULT NOW()
);

-- Mesas ejemplo
INSERT INTO TB_TABLES (TABLE_NUMBER, CAPACITY, LOCATION) VALUES
(1, 2, 'Interior'),
(2, 2, 'Interior'),
(3, 4, 'Interior'),
(4, 4, 'Terraza'),
(5, 6, 'Terraza'),
(6, 8, 'VIP');

-- ============================================
-- TABLA DE RESERVAS
-- ============================================
CREATE TABLE TB_RESERVATIONS (
  ID_RESERVATION SERIAL PRIMARY KEY,
  ID_USER UUID NOT NULL REFERENCES TB_USERS(ID_USER) ON DELETE CASCADE,
  ID_TABLE INT NULL REFERENCES TB_TABLES(ID_TABLE),
  RESERVATION_DATE DATE NOT NULL,
  RESERVATION_TIME TIME NOT NULL,
  NUM_PEOPLE INT NOT NULL CHECK (NUM_PEOPLE > 0),
  CUSTOMER_NAME VARCHAR(100) NOT NULL,
  CUSTOMER_PHONE VARCHAR(15) NOT NULL,
  CUSTOMER_EMAIL VARCHAR(100) NOT NULL,
  SPECIAL_NOTES TEXT,
  STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
  -- Estados: 'PENDIENTE', 'CONFIRMADA', 'RECHAZADA', 'CANCELADA', 'COMPLETADA'
  ATTENDED_BY UUID REFERENCES TB_USERS(ID_USER), -- ID del recepcionista que atendió
  RESPONSE_NOTES TEXT, -- Notas del recepcionista al aceptar/rechazar
  CREATED_AT TIMESTAMP DEFAULT NOW(),
  UPDATED_AT TIMESTAMP DEFAULT NOW(),
  CONSTRAINT chk_status_valid CHECK (STATUS IN ('PENDIENTE', 'CONFIRMADA', 'RECHAZADA', 'CANCELADA', 'COMPLETADA')),
  CONSTRAINT unique_reservation UNIQUE(ID_TABLE, RESERVATION_DATE, RESERVATION_TIME)
);

CREATE TABLE TB_GALLERY (
  ID_GALLERY SERIAL PRIMARY KEY,
  TITLE VARCHAR(100),
  DESCRIPTION TEXT,
  IMAGE_URL TEXT NOT NULL,
  CATEGORY VARCHAR(50),
  FEATURED BOOLEAN,
  IS_VISIBLE BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP DEFAULT NOW()
);

-- ============================================
-- ÍNDICES PARA MEJOR PERFORMANCE
-- ============================================
CREATE INDEX idx_users_email ON TB_USERS(EMAIL);
CREATE INDEX idx_users_role ON TB_USERS(ID_ROLE);
CREATE INDEX idx_items_category ON TB_ITEMS(ID_CAT);
CREATE INDEX idx_items_available ON TB_ITEMS(IS_AVAILABLE);
CREATE INDEX idx_reservations_user ON TB_RESERVATIONS(ID_USER);
CREATE INDEX idx_reservations_date ON TB_RESERVATIONS(RESERVATION_DATE);
CREATE INDEX idx_reservations_status ON TB_RESERVATIONS(STATUS);
CREATE INDEX idx_reservations_table ON TB_RESERVATIONS(ID_TABLE);

CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.UPDATED_AT = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_reservations
BEFORE UPDATE ON TB_RESERVATIONS
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();
